---
- name: Setup Kubernetes Master Node
  hosts: masters
  tasks:
    - name: get update
      command: sudo apt-get update

    - name: install pip3
      command: sudo apt-get install python3-pip -y

    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes

    - name: Set PATH and KUBECONFIG for kubectl
      lineinfile:
        path: "~/.bashrc"
        line: "{{ item }}"
      with_items:
        - "export PATH=$PATH:/var/lib/rancher/rke2/bin/"
        - "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml"

    - name: Adjust permissions for kubectl config
      file:
        path: /etc/rancher/rke2/rke2.yaml
        mode: '0644'

    #- name: Create cattle-system namespace
    #  command: sudo /usr/local/bin/kubectl create namespace cattle-system

    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present

    - name: Download and Install Helm
      block:
        - name: Download Helm script
          get_url:
            url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            dest: /tmp/get_helm.sh
            mode: '0700'
        - name: Install Helm
          command: /tmp/get_helm.sh

    - name: Check helm version
      command: helm version
      register: helm_version
      changed_when: false

    - name: Display helm version
      debug:
        var: helm_version.stdout

    - name: Add jetstack helm repo
      command: helm repo add jetstack https://charts.jetstack.io

    - name: Create cert-manager namespace
      command: /usr/local/bin/kubectl create namespace cert-manager

    - name: Install cert-manager with Helm
      command: >
        helm install cert-manager jetstack/cert-manager
        --namespace cert-manager
        --version v1.12
        --set installCRDs=true

    - name: Add rancher-stable helm repo
      command: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

    - name: Install Rancher with Helm
      command: >
        helm install rancher rancher-latest/rancher
        --namespace cattle-system
        --set hostname=rancher.my.org
